### ISSUE TITLE
.info file is not syntax-highlighted properly

### ISSUE THREAD

**Issue by gh640** [robballou/drupal-sublimetext#12]
Thank you for the useful package :)

I have a problem with my .info file. I made a .info file using Libraries API module with like the following. The last 2 lines for `flies` is not highlighted with this package.

```text
name = normalize.css
vendor url = https://github.com/necolas/normalize.css
download url = https://github.com/necolas/normalize.css/releases
download file url = https://github.com/necolas/normalize.css/archive/7.0.0.tar.gz
version arguments[file] = 'package.json'
version arguments[pattern] = /"version": "(\d+\.\d+.\d+)"/
version arguments[lines] = 3
files[css][normalize.css][group] = CSS_SYSTEM
files[css][normalize.css][every page] = TRUE
```

It seems to be because `.` is not covered in the regular expression for this line.

https://github.com/robballou/drupal-sublimetext/blob/master/Drupal%20Info%20File/Drupal%20Info%20Files.tmLanguage#L29

**Comment by gh640** [comment]
The regular expression used in Drupal is found in:

https://api.drupal.org/api/drupal/includes%21common.inc/function/drupal_parse_info_format/7.x

I'd like this PR to be merged if you don't mind. Thank you in advance.

**Comment by gh640** [comment]
This repo looks like abandoned.

**Comment by robballou** [comment]
More or less. I don't use Sublime or Drupal anymore. I'm willing to point links to a new source or add maintainers if people are interested in taking it on.
